# Generated by Django 6.0.4 on 2026-04-25 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto_fijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gastos_fijos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.categoria')),
            ],
            options={
                'verbose_name': 'Gasto Fijo',
                'verbose_name_plural': 'Gastos Fijos',
            },
        ),
    ]
