# Generated by Django 6.0.4 on 2026-04-26 12:50

import django.db.models.deletion
import gastos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_gasto_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('icono', models.ImageField(upload_to='categorias_ingreso/')),
            ],
            options={
                'verbose_name': 'Categoría ingreso',
                'verbose_name_plural': 'Categorías ingreso',
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gastos.categoria_ingreso'),
            preserve_default=False,
        ),
    ]
