# Generated by Django 6.0.4 on 2026-04-26 15:25

import gastos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_categoria_ingreso_ingreso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(max_length=10, validators=[gastos.models.validar_tamano]),
        ),
        migrations.AlterField(
            model_name='categoria_ingreso',
            name='icono',
            field=models.CharField(max_length=10, validators=[gastos.models.validar_tamano]),
        ),
    ]
