# Generated by Django 6.0.4 on 2026-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_categoria_usuario_categoria_ingreso_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto_fijo',
            name='monto_cuotas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
