# Generated by Django 6.0.4 on 2026-05-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_gasto_fijo_monto_cuotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto_fijo',
            name='monto_cuotas',
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('pagada', models.BooleanField(default=False)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_rel', to='gastos.gasto_fijo')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
