# Generated by Django 6.0.4 on 2026-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_alter_cuota_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto_fijo',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
