# Generated by Django 6.0.4 on 2026-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_gasto_fijo_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto_fijo',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
